### ISSUE TITLE
why re-create the training/evaluation datasets after evaluation? 

### ISSUE THREAD

**Issue by joelive** [KyoungYeulLee/3Cnet#9]
Thank you for presenting your work.
1.why re-create the training/evaluation datasets after evaluation? 
2.According to your paper there are two step training process. But I did not find them in the code.
3.I found the truncated protein data in the data dir. Is the model able to predict truncated protein too? How to train the merged data?
4.How to generate SNVBOX_features for new mutations?

**Comment by Kylee3bill** [comment]
Issues have been resolved by version 2 release. Thanks
